version: "3.7"

services:

  liv2mongbot:
        build: ./liv2mong
        container_name: live2mong
        restart: always
        environment:
            - APP_NAME=MyLiv2MongoDB
        logging:
            driver: "json-file"
            options:
              max-size: "200k"
              max-file: "5"
